OSTicket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TKTUsers.urls'), name="TKTUsers"),
    path('TKTAdmin/', include('TKTAdmin.urls'), name="TKTAdmin"),
    path('TKTAgent/', include('TKTAgent.urls'), name="TKTAgent"),
]

TKTAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'TKTAdmin'

urlpatterns = [
    path('', home, name="home"),
    path('admin_login', admin_login, name="admin_login"),
    path('admin_dashboard', admin_dashboard, name="admin_dashboard"),
    path('admin_logout', admin_logout, name="admin_logout"),

    path('view_agent_role', view_agent_role, name="view_agent_role"),
    path('create_agent_role', create_agent_role, name="create_agent_role"),
    path('edit_agent_role/<int:id>', edit_agent_role, name="edit_agent_role"),

    path('view_category', view_category, name="view_category"),
    path('create_category', create_category, name="create_category"),
    path('edit_category/<int:id>', edit_category, name="edit_category"),

    path('view_ticket_status_choice', view_ticket_status_choice, name="view_ticket_status_choice"),
    path('create_ticket_status_choice', create_ticket_status_choice, name="create_ticket_status_choice"),
    path('edit_ticket_status_choice/<int:id>', edit_ticket_status_choice, name="edit_ticket_status_choice"),

    path('view_technology_stack', view_technology_stack, name="view_technology_stack"),
    path('create_technology_stack', create_technology_stack, name="create_technology_stack"),
    path('edit_technology_stack/<int:id>', edit_technology_stack, name="edit_technology_stack"),

    path('view_Issue_Category', view_Issue_Category, name="view_Issue_Category"),
    path('create_Issue_Category', create_Issue_Category, name="create_Issue_Category"),
    path('edit_Issue_Category/<int:id>', edit_Issue_Category, name="edit_Issue_Category"),

    path('view_agent_list', view_agent_list, name="view_agent_list"),
    path('create_agent_list', create_agent_list, name="create_agent_list"),
    path('edit_agent_list/<int:id>', edit_agent_list, name="edit_agent_list"),


    path('view_tickets_list', view_tickets_list, name="view_tickets_list"),
    path('assign_ticket/<int:id>', assign_ticket, name="assign_ticket"),


]

TKTAdmin/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash


# Create your views here.
def home(request):
    pass


def admin_login(request):
    if request.method == 'POST':
        UserLoginForm_obj = UserLoginForm(
            request=request, data=request.POST)
        if UserLoginForm_obj.is_valid():
            uname = UserLoginForm_obj.cleaned_data['username']
            passwd = UserLoginForm_obj.cleaned_data['password']
            user = authenticate(username=uname, password=passwd)
            if user is not None:
                login(request, user)
                messages.success(request, "Login Successfully")
                return redirect('TKTAdmin:admin_dashboard')
            else:
                messages.error(request, "User does not exist")
                return redirect('TKTAdmin:admin_login')
        else:
            messages.error(
                request, "Invalid Details . Please login with correct details")
            return redirect('TKTAdmin:admin_login')
    else:
        UserLoginForm_obj = UserLoginForm()
        return render(request, 'TKTAdmin/admin_login.html', {'UserLoginForm_obj': UserLoginForm_obj})


def admin_dashboard(request):
    return render(request, 'TKTAdmin/admin_dashboard.html')


def admin_logout(request):
    logout(request)
    return redirect('TKTAdmin:admin_login')


######################################################

def view_agent_role(request):
    Agent_Role_obj = Agent_Role.objects.all()
    return render(request, 'TKTAdmin/admin_view_agent_role.html', {'Agent_Role_obj': Agent_Role_obj})


def create_agent_role(request):
    if request.method == 'POST':
        AgentRoleForm_obj = AgentRoleForm(request.POST)
        if AgentRoleForm_obj.is_valid():
            AgentRoleForm_obj.save()
            messages.success(request, "Role Created Successfully")
            return redirect('TKTAdmin:view_agent_role')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/admin_create_agent_role.html', {'AgentRoleForm_obj': AgentRoleForm_obj})

    else:
        AgentRoleForm_obj = AgentRoleForm()
        return render(request, 'TKTAdmin/admin_create_agent_role.html', {'AgentRoleForm_obj': AgentRoleForm_obj})


def edit_agent_role(request, id):
    if request.method == 'POST':
        print("POST CALLING")
        Agent_Role_obj = Agent_Role.objects.get(pk=id)
        AgentRoleForm_obj = AgentRoleForm(request.POST, instance=Agent_Role_obj)
        if AgentRoleForm_obj.is_valid():
            AgentRoleForm_obj.save()
            messages.success(request, "Role Edited Successfully")
            return redirect('TKTAdmin:view_agent_role')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/admin_edit_agent_role.html', {'AgentRoleForm_obj': AgentRoleForm_obj})

    else:
        print("GET CALLING")
        Agent_Role_obj = Agent_Role.objects.get(pk=id)
        print(Agent_Role_obj)
        AgentRoleForm_obj = AgentRoleForm(instance=Agent_Role_obj)
        return render(request, 'TKTAdmin/admin_edit_agent_role.html', {'AgentRoleForm_obj': AgentRoleForm_obj})


#####################################################################

def view_category(request):
    Category_obj = Category.objects.all()
    return render(request, 'TKTAdmin/admin_view_category.html', {'Category_obj': Category_obj})


def create_category(request):
    if request.method == 'POST':
        CategoryForm_obj = CategoryForm(request.POST)
        if CategoryForm_obj.is_valid():
            CategoryForm_obj.save()
            messages.success(request, "Category Created Successfully")
            return redirect('TKTAdmin:view_category')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/admin_create_category.html', {'CategoryForm_obj': CategoryForm_obj})

    else:
        CategoryForm_obj = CategoryForm()
        return render(request, 'TKTAdmin/admin_create_category.html', {'CategoryForm_obj': CategoryForm_obj})


def edit_category(request, id):
    if request.method == 'POST':
        print("POST CALLING")
        Category_obj = Category.objects.get(pk=id)
        CategoryForm_obj = CategoryForm(request.POST, instance=Category_obj)
        if CategoryForm_obj.is_valid():
            CategoryForm_obj.save()
            messages.success(request, "Category Edited Successfully")
            return redirect('TKTAdmin:view_category')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/admin_edit_category.html', {'CategoryForm_obj': CategoryForm_obj})

    else:
        print("GET CALLING")
        Category_obj = Category.objects.get(pk=id)
        print(Category_obj)
        CategoryForm_obj = CategoryForm(instance=Category_obj)
        return render(request, 'TKTAdmin/admin_edit_category.html', {'CategoryForm_obj': CategoryForm_obj})


###############################################


def view_ticket_status_choice(request):
    Ticket_status_choice_obj = Ticket_status_choice.objects.all()
    return render(request, 'TKTAdmin/view_ticket_status_choice.html',
                  {'Ticket_status_choice_obj': Ticket_status_choice_obj})


def create_ticket_status_choice(request):
    if request.method == 'POST':
        Ticket_status_choiceForm_obj = Ticket_status_choiceForm(request.POST)
        if Ticket_status_choiceForm_obj.is_valid():
            Ticket_status_choiceForm_obj.save()
            messages.success(request, "Ticket Status Choice Created Successfully")
            return redirect('TKTAdmin:view_ticket_status_choice')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/admin_create_ticket_status_choice.html',
                          {'Ticket_status_choiceForm_obj': Ticket_status_choiceForm_obj})

    else:
        Ticket_status_choiceForm_obj = Ticket_status_choiceForm()
        return render(request, 'TKTAdmin/admin_create_ticket_status_choice.html',
                      {'Ticket_status_choiceForm_obj': Ticket_status_choiceForm_obj})


def edit_ticket_status_choice(request, id):
    if request.method == 'POST':
        print("POST CALLING")
        Ticket_status_choice_obj = Ticket_status_choice.objects.get(pk=id)
        Ticket_status_choiceForm_obj = Ticket_status_choiceForm(request.POST, instance=Ticket_status_choice_obj)
        if Ticket_status_choiceForm_obj.is_valid():
            Ticket_status_choiceForm_obj.save()
            messages.success(request, "Ticket Status Choice Edited Successfully")
            return redirect('TKTAdmin:view_ticket_status_choice')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/admin_edit_ticket_status_choice.html',
                          {'Ticket_status_choiceForm_obj': Ticket_status_choiceForm_obj})

    else:
        print("GET CALLING")
        Ticket_status_choice_obj = Ticket_status_choice.objects.get(pk=id)
        print(Ticket_status_choice_obj)
        Ticket_status_choiceForm_obj = Ticket_status_choiceForm(instance=Ticket_status_choice_obj)
        return render(request, 'TKTAdmin/admin_edit_ticket_status_choice.html',
                      {'Ticket_status_choiceForm_obj': Ticket_status_choiceForm_obj})


###############################################

def view_technology_stack(request):
    technology_stack_obj = technology_stack.objects.all()
    return render(request, 'TKTAdmin/view_technology_stack.html',
                  {'technology_stack_obj': technology_stack_obj})


def create_technology_stack(request):
    if request.method == 'POST':
        technology_stackForm_obj = technology_stackForm(request.POST)
        if technology_stackForm_obj.is_valid():
            technology_stackForm_obj.save()
            messages.success(request, "Ticket Status Choice Created Successfully")
            return redirect('TKTAdmin:view_technology_stack')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/create_technology_stack.html',
                          {'technology_stackForm_obj': technology_stackForm_obj})

    else:
        technology_stackForm_obj = technology_stackForm()
        return render(request, 'TKTAdmin/create_technology_stack.html',
                      {'technology_stackForm_obj': technology_stackForm_obj})


def edit_technology_stack(request, id):
    if request.method == 'POST':
        print("POST CALLING")
        technology_stack_obj = technology_stack.objects.get(pk=id)
        technology_stackForm_obj = technology_stackForm(request.POST, instance=technology_stack_obj)
        if technology_stackForm_obj.is_valid():
            technology_stackForm_obj.save()
            messages.success(request, "Technology Stack Edited Successfully")
            return redirect('TKTAdmin:view_technology_stack')
        else:
            messages.error(request, "Invalid Data Entered")
            return render(request, 'TKTAdmin/edit_technology_stack.html',
                          {'technology_stackForm_obj': technology_stackForm_obj})

    else:
        print("GET CALLING")
        technology_stack_obj = technology_stack.objects.get(pk=id)
        print(technology_stack_obj)
        technology_stackForm_obj = technology_stackForm(instance=technology_stack_obj)
        return render(request, 'TKTAdmin/edit_technology_stack.html',
                      {'technology_stackForm_obj': technology_stackForm_obj})


###############################################


def view_Issue_Category(request):
    Issue_Category_obj = Issue_Category.objects.all()
    return render(request, 'TKTAdmin/view_Issue_Category.html',

TKTAdmin/templates/TKTAdmin/admin_dashboard.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block admin_dashboard %}

<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">
                Dashboard
            </h6>
            <h1 class="mb-5">Dashboard</h1>
        </div>
        <div>
            <h4>Welcome {{request.user.email}}</h4>
            {% if messages %} {% for message in messages %}
            <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>
                {{message}}
            </p>
            {% endfor %} {% endif %}
        </div>

        <div class="row g-5">
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa fa-book text-primary mb-4"></i>
                        <h4 class="mb-3">Agent Roles</h4>
                        <a href="{% url 'TKTAdmin:view_agent_role'%}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-server text-primary mb-4"></i>
                        <h4 class="mb-3">Create Agent</h4>
                        <a href="{% url 'TKTAdmin:view_agent_list' %}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-cog text-primary mb-4"></i>
                        <h4 class="mb-3"> Technology Stack</h4>
                        <a href="{% url 'TKTAdmin:view_technology_stack' %}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa-video-camera text-primary mb-4"></i>
                        <i class="fa fa-3x fa fa-camera-retro text-primary mb-4"></i>

                        <h4 class="mb-3"> Website Category</h4>
                        <a href="{% url 'TKTAdmin:view_category' %}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-check-square text-primary mb-4"></i>
                        <h4 class="mb-3">Ticket Status Choice</h4>
                        <a href="{% url 'TKTAdmin:view_ticket_status_choice' %}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-folder text-primary mb-4"></i>
                        <a href="{% url 'TKTAdmin:view_tickets_list' %}">
                            <h4 class="mb-3">View Tickets</h4>
                        </a>
                        <a href="{% url 'TKTAdmin:view_tickets_list' %}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>



                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-folder text-primary mb-4"></i>
                        <a href="{% url 'TKTAdmin:view_Issue_Category' %}">
                            <h4 class="mb-3"> Issue Category</h4>
                        </a>
                        <a href="{% url 'TKTAdmin:view_Issue_Category' %}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-folder text-primary mb-4"></i>
                        <a href="{% url 'TKTAdmin:admin_logout'%}">
                            <h4 class="mb-3">Logout</h4>
                        </a>
                        <a href="#">
                            <h5 class="mb-3">Logout</h5>
                        </a>
                    </div>



                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

TKTAdmin/templates/TKTAdmin/create_issue_category.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block admin_create_issue_category %}

<div class="container h-custom">
    <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title bg-white text-center text-primary px-3">
            Create Issue Category
        </h6>
        <h1 class="mb-3">Create Issue Category</h1>
    </div>

  <div class="row mb-4">
    <div class="col-6">
      <h5 class="text-start mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:admin_dashboard' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Dashboard</a
        >
      </h5>
    </div>
    <div class="col-6">
      <h5 class="text-end mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:view_Issue_Category' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Issue Category List
        </a>
      </h5>
    </div>
  </div>

   <div>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
        {% endif %}
  </div>
    <div class="row justify-content-md-center">
         <div class='col-8 card px-4 py-8 mx-5 shadow mb-5' style="background-color: #6C3C8203; border-radius:10px !important" >
              <form method="POST" autocomplete="off" novalidate>
                  {% csrf_token %}

              <div class="form-group my-3">
                    <label for="inputEmail" class="mb-3 fs-5 fw-bold px-1">Enter Issue Category</label>
                    <div>{{ Issue_CategoryForm_obj.Issue_Category_name }}</div>
                    <span class="text-danger">{{ Issue_CategoryForm_obj.Issue_Category_name.errors}}</span>
              </div>

              <div class="col-2 mb-3">
                  <button type="submit" class="btn btn-primary mt-2 rounded-3">Create  </button>
              </div>
                  </form>
         </div>
    </div>
</div>

{% endblock %}

TKTAdmin/templates/TKTAdmin/edit_issue_category.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block admin_edit_issue_category %}
<div class="container h-custom">
    <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title bg-white text-center text-primary px-3">
            Edit Issue Category
        </h6>
        <h1 class="mb-3">Edit Issue Category</h1>
    </div>

  <div class="row mb-4">
    <div class="col-6">
      <h5 class="text-start mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:admin_dashboard' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Dashboard</a
        >
      </h5>
    </div>
    <div class="col-6">
      <h5 class="text-end mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:view_Issue_Category' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to List of Issue Category
        </a>
      </h5>
    </div>
  </div>

   <div>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
        {% endif %}
  </div>
    <div class="row justify-content-md-center">
         <div class='col-8 card px-4 py-8 mx-5 shadow mb-5' style="background-color: #6C3C8203; border-radius:10px !important" >
              <form method="POST" autocomplete="off" novalidate>
                  {% csrf_token %}

              <div class="form-group my-3">
                    <label for="technology_name" class="mb-3 fs-5 fw-bold px-1">Issue Category Name</label>
                    <div>{{ Issue_CategoryForm_obj.Issue_Category_name }}</div>
                    <span class="text-danger">{{ Issue_CategoryForm_obj.Issue_Category_name.errors}}</span>
              </div>

              <div class="col-2 mb-3">
                  <button type="submit" class="btn btn-primary mt-2 rounded-3">Edit </button>
              </div>
                  </form>
         </div>
    </div>
</div>

{% endblock %}

TKTAdmin/templates/TKTAdmin/view_Issue_Category.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block admin_view_Issue_category %}
<div class="container p-5 ">
    <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title bg-white text-center text-primary px-3">
            Issue Category List
        </h6>
        <h1 class="mb-3">Issue Category List</h1>
    </div>

  <div class="row mb-4">
    <div class="col-6">
      <h5 class="text-start mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:admin_dashboard' %}"
          style="background-color: rgb(63, 127, 165); border-radius: 10px"
          >Back to Dashboard</a
        >
      </h5>
    </div>
    <div class="col-6">
      <h5 class="text-end mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:create_Issue_Category' %}"
          style="background-color: rgb(63, 127, 165); border-radius: 10px"
          >Create New Issue Category
        </a>
      </h5>
    </div>
  </div>

   <div>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
        {% endif %}
  </div>
  <div class="row d-flex justify-content-center align-items-center">
    <table class="table table-striped" id="mytable" style="width: 100%">
      <thead>
        <tr>
          <th>S.No.</th>
          <th>Issue CategoryName</th>
          <th>Created Date </th>
          <th>Last Updated Date</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        {% for data in Issue_Category_obj %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{data.Issue_Category_name}}</td>
          <td>{{data.Issue_Category_created_date}}</td>
          <td>{{data.Issue_Category_update_date}}</td>
            <td><a href="{% url 'TKTAdmin:edit_Issue_Category' data.id %}">Edit</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- CIP Server End -->

<script>
  $(document).ready(function () {
    $("#mytable").dataTable({
      buttons: ["copy", "csv", "excel", "pdf", "print"],
      info: true,
      paging: true,
    });
  });
</script>
{% endblock %}

TKTAdmin/templates/TKTAdmin/view_agent_list.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block admin_view_agent_list %}
<div class="container p-5 ">
    <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title bg-white text-center text-primary px-3">
            Agent List
        </h6>
        <h1 class="mb-3">Agent List</h1>
    </div>

  <div class="row mb-4">
    <div class="col-6">
      <h5 class="text-start mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:admin_dashboard' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Dashboard</a
        >
      </h5>
    </div>
    <div class="col-6">
      <h5 class="text-end mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:create_agent_list' %}"
          style="background-color: #886363; border-radius: 10px"
          >Create New Agent
        </a>
      </h5>
    </div>
  </div>
   <div>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
        {% endif %}
  </div>
  <div class="row d-flex justify-content-center align-items-center">
    <table class="table table-striped" id="mytable" style="width: 100%">
      <thead>
        <tr>
          <th>S.No.</th>
          <th>Name</th>
          <th>Role</th>
          <th>Created Date </th>
          <th>Status</th>
          <th>Expert In</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        {% for data in Agent_obj %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{data.Agent_name}}</td>
            <td>{{data.Agent_role}}</td>
            <td>{{data.Agent_created_date}}</td>
            <td>{{data.Agent_status}}</td>
            <td>{{data.Agent_expert}}</td>
            <td><a href="{% url 'TKTAdmin:edit_agent_list' data.id %}">Edit</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- CIP Server End -->

<script>
  $(document).ready(function () {
    $("#mytable").dataTable({
      buttons: ["copy", "csv", "excel", "pdf", "print"],
      info: true,
      paging: true,
    });
  });
</script>
{% endblock %}

TKTAdmin/templates/TKTAdmin/view_technology_stack.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block admin_view_technology_stack %}
<div class="container p-5 ">
    <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title bg-white text-center text-primary px-3">
            Technology Stack List
        </h6>
        <h1 class="mb-3">Technology Stack List</h1>
    </div>

  <div class="row mb-4">
    <div class="col-6">
      <h5 class="text-start mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:admin_dashboard' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Dashboard</a
        >
      </h5>
    </div>
    <div class="col-6">
      <h5 class="text-end mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:create_technology_stack' %}"
          style="background-color: #886363; border-radius: 10px"
          >Create New Technology Stack
        </a>
      </h5>
    </div>
  </div>

   <div>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
        {% endif %}
  </div>
  <div class="row d-flex justify-content-center align-items-center">
    <table class="table table-striped" id="mytable" style="width: 100%">
      <thead>
        <tr>
          <th>S.No.</th>
          <th>Technology Stack Name</th>
          <th>Created Date </th>
          <th>Last Updated Date</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        {% for data in technology_stack_obj %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{data.technology_name}}</td>
          <td>{{data.technology_stack_created_date}}</td>
          <td>{{data.technology_stack_update_date}}</td>
            <td><a href="{% url 'TKTAdmin:edit_technology_stack' data.id %}">Edit</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- CIP Server End -->

<script>
  $(document).ready(function () {
    $("#mytable").dataTable({
      buttons: ["copy", "csv", "excel", "pdf", "print"],
      info: true,
      paging: true,
    });
  });
</script>
{% endblock %}