OSTicket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TKTUsers.urls'), name="TKTUsers"),
    path('TKTAdmin/', include('TKTAdmin.urls'), name="TKTAdmin"),
    path('TKTAgent/', include('TKTAgent.urls'), name="TKTAgent"),
]

TKTAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'TKTAdmin'

urlpatterns = [
    path('', home, name="home"),
    path('admin_login', admin_login, name="admin_login"),
    path('admin_dashboard', admin_dashboard, name="admin_dashboard"),
    path('admin_logout', admin_logout, name="admin_logout"),

    path('view_agent_role', view_agent_role, name="view_agent_role"),
    path('create_agent_role', create_agent_role, name="create_agent_role"),
    path('edit_agent_role/<int:id>', edit_agent_role, name="edit_agent_role"),

    path('view_category', view_category, name="view_category"),
    path('create_category', create_category, name="create_category"),
    path('edit_category/<int:id>', edit_category, name="edit_category"),

    path('view_ticket_status_choice', view_ticket_status_choice, name="view_ticket_status_choice"),
    path('create_ticket_status_choice', create_ticket_status_choice, name="create_ticket_status_choice"),
    path('edit_ticket_status_choice/<int:id>', edit_ticket_status_choice, name="edit_ticket_status_choice"),

    path('view_technology_stack', view_technology_stack, name="view_technology_stack"),
    path('create_technology_stack', create_technology_stack, name="create_technology_stack"),
    path('edit_technology_stack/<int:id>', edit_technology_stack, name="edit_technology_stack"),

    path('view_Issue_Category', view_Issue_Category, name="view_Issue_Category"),
    path('create_Issue_Category', create_Issue_Category, name="create_Issue_Category"),
    path('edit_Issue_Category/<int:id>', edit_Issue_Category, name="edit_Issue_Category"),

    path('view_agent_list', view_agent_list, name="view_agent_list"),
    path('create_agent_list', create_agent_list, name="create_agent_list"),
    path('edit_agent_list/<int:id>', edit_agent_list, name="edit_agent_list"),


    path('view_tickets_list', view_tickets_list, name="view_tickets_list"),
    path('assign_ticket/<int:id>', assign_ticket, name="assign_ticket"),


]

TKTAgent/urls.py
from django.contrib import admin
from django.urls import path, include
from TKTAgent.views import *

app_name = 'TKTAgent'

urlpatterns = [
    path('agent_login', agent_login, name="agent_login"),
    path('agent_dashboard', agent_dashboard, name="agent_dashboard"),
    path('view_tickets_list_agent', view_tickets_list_agent, name="view_tickets_list_agent"),
    path('agent_resolve_ticket/<int:id>', agent_resolve_ticket, name="agent_resolve_ticket"),
]

TKTAgent/models.py
from django.db import models

# Create your models here.

TKTAgent/views.py
# Create your views here.
from django.shortcuts import render, redirect
from TKTAdmin.forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash

from TKTUsers.models import *


def agent_login(request):
    if request.method == 'POST':
        AgentLoginForm_obj = UserLoginForm(request=request, data=request.POST)
        if AgentLoginForm_obj.is_valid():
            uname = AgentLoginForm_obj.cleaned_data['username']
            passwd = AgentLoginForm_obj.cleaned_data['password']
            user = authenticate(username=uname, password=passwd)
            if user is not None:
                login(request, user)
                messages.success(request, "Login Successfully")
                return redirect('TKTAgent:agent_dashboard')
            else:
                messages.error(request, "Agent does not exist")
                return render(request, 'TKTAgent/agent_login.html', {'AgentLoginForm_obj': AgentLoginForm_obj})
        else:
            messages.error(request, "Invalid Details . Please login with correct details")
            return render(request, 'TKTAgent/agent_login.html', {'AgentLoginForm_obj': AgentLoginForm_obj})
    else:
        AgentLoginForm_obj = UserLoginForm()
        return render(request, 'TKTAgent/agent_login.html', {'AgentLoginForm_obj': AgentLoginForm_obj})


def agent_dashboard(request):
    return render(request, 'TKTAgent/agent_dashboard.html')


def view_tickets_list_agent(request):
    Agent_TicketDetail_obj = TicketDetail.objects.filter(ticket_assigned_to=2,ticket_status = 2)
    return render(request, 'TKTAgent/agent_ticket_list.html', {'Agent_TicketDetail_obj': Agent_TicketDetail_obj})


def agent_resolve_ticket(request, id):
    if request.method == "POST":
        TicketDetail_obj = TicketDetail.objects.get(pk=id)
        Ticket_Form_obj = Ticket_Form_Agent(request.POST, instance=TicketDetail_obj)
        if Ticket_Form_obj.is_valid():
            temp_obj = Ticket_Form_obj.save(commit=False)
            temp_obj.ticket_status = Ticket_Form_obj.cleaned_data['ticket_status']
            temp_obj.save()

            messages.success(request, "Resolved  Successfully")
            return redirect('TKTAgent:view_tickets_list_agent')
        else:
            messages.error(request, "Invalid Data ")
            return render(request, 'TKTAgent/resolve_Ticket.html',
                          {'Ticket_Form_obj': Ticket_Form_obj})
    else:
        TicketDetail_obj = TicketDetail.objects.get(pk=id)
        Ticket_Form_obj = Ticket_Form_Agent(instance=TicketDetail_obj)
        return render(request, 'TKTAgent/resolve_Ticket.html',
                      {'Ticket_Form_obj': Ticket_Form_obj})

TKTAgent/templates/TKTAgent/agent_dashboard.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block agent_dashboard %}

<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">
                Agent Dashboard
            </h6>
            <h1 class="mb-5">Agent Dashboard</h1>
        </div>
        <div>
            <h4>Welcome {{request.user.email}}</h4>
            {% if messages %} {% for message in messages %}
            <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>
                {{message}}
            </p>
            {% endfor %} {% endif %}
        </div>

        <div class="row g-5">


            <div class="col-lg-6 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-folder text-primary mb-4"></i>
                        <a href="{% url 'TKTAgent:view_tickets_list_agent' %}">
                            <h4 class="mb-3">View Tickets</h4>
                        </a>
                        <a href="{% url 'TKTAgent:view_tickets_list_agent' %}">
                            <h5 class="mb-3">Details</h5>
                        </a>
                    </div>



                </div>
            </div>

            <div class="col-lg-6 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div
                        class="service-item text-center pt-3"
                        style="box-shadow: 12px 12px 8px -3px #7c3e6673"
                >
                    <div class="p-4">
                        <i class="fa fa-3x fa fa-folder text-primary mb-4"></i>
                        <a href="{% url 'TKTAdmin:admin_logout'%}">
                            <h4 class="mb-3">Logout</h4>
                        </a>
                        <a href="#">
                            <h5 class="mb-3">Logout</h5>
                        </a>
                    </div>



                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

TKTAgent/templates/TKTAgent/agent_login.html
{% extends 'TKTUsers/base.html'%}
{% block agentlogin %}

<div class="container my-5 rounded-8">
           <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Agent Login</h6>
            <h1 class="mb-4">Agent Login</h1>
        </div>
     <div class="row justify-content-md-center">
            {% if messages %}
                    {% for message in messages %}
                        <div class="col-8 m-0 p-2 ps-4 fs-6 fw-semibold alert alert-{{message.extra_tags}}">{{message}}</div>
                    {% endfor %}
                {% endif %}
            <div style="color:red" class="col-8">
                {% if UserLoginForm_obj.non_field_errors %}
                    {% for error in UserLoginForm_obj.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong >{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
     </div>
    <div class="row justify-content-md-center">
         <div class='col-8 card px-4 py-8 mx-5 shadow mb-5' style="background-color: #6C3C8203; border-radius:10px !important" >
              <form method="POST" autocomplete="off" novalidate>
                  {% csrf_token %}

              <div class="form-group my-3">
                    <label for="inputEmail" class="mb-1 fs-5 fw-bold px-1">Email Address</label>
                    <div>{{ AgentLoginForm_obj.username }}</div>
                    <span class="text-danger">{{ AgentLoginForm_obj.username.errors}}</span>
              </div>

             <div class="form-group my-3">
                    <label for="inputPassword" class="mb-1 fs-5 fw-bold px-1">Password <i class="fa fa-question-circle fa-sm" aria-hidden="true" title="Password must contain minimum 8 characters with minimum 1 uppercase character, 1 lowercase character, 1 number and 1 special symbol"></i></label>
                    <div>{{ AgentLoginForm_obj.password }} </div>
                    <span class="text-danger">{{ AgentLoginForm_obj.password.errors}}</span>
             </div>
              <div class="col-2 ">
                  <button type="submit" class="btn btn-primary mt-2">Login</button>
              </div>
                  </form>
         </div>
    </div>
</div>

{% endblock %}

TKTAgent/templates/TKTAgent/agent_ticket_list.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block agent_view_ticket_list %}
<div class="container-fluid p-5 ">
    <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title bg-white text-center text-primary px-3">
            Assigned Ticket List
        </h6>
        <h1 class="mb-3">Assigned Ticket List</h1>
    </div>

  <div class="row mb-4">
    <div class="col-6">
      <h5 class="text-start mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAdmin:admin_dashboard' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Dashboard</a
        >
      </h5>
    </div>
    <div class="col-6">
      <h5 class="text-end mb-4">
        <a
          class="text-white btn btn-info"
          href="#"
          style="background-color: #886363; border-radius: 10px"
          >Create New Ticket
        </a>
      </h5>
    </div>
  </div>
   <div>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
        {% endif %}
  </div>
  <div class="row d-flex justify-content-center align-items-center">
    <table class="table table-striped" id="mytable" style="width: 100%">
      <thead>
        <tr>
          <th>S.No.</th>
          <th>Website Name</th>
          <th>Website URL</th>
          <th>Website Description </th>
          <th>Website Category</th>
          <th>Issue Related To</th>
          <th>Ticket Raised By</th>
          <th>Website Technology</th>
         <th>Ticket Assigned to</th>
            <th>Status</th>
          <th>Assign</th>
        </tr>
      </thead>
      <tbody>
        {% for data in Agent_TicketDetail_obj %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{data.websitename}}</td>
            <td>{{data.websiteurl}}</td>
            <td>{{data.website_description}}</td>
            <td>{{data.website_category}}</td>
            <td>{{data.Issue_Related_To}}</td>
            <td>{{data.ticket_raised_by}}</td>
            <td>{{data.website_technology}}</td>
            <td>{{data.ticket_assigned_to}}</td>
            <td>{{data.ticket_status}}</td>
            <td><a href="{% url 'TKTAgent:agent_resolve_ticket' data.id%}">Assign</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- CIP Server End -->

<script>
  $(document).ready(function () {
    $("#mytable").dataTable({
      buttons: ["copy", "csv", "excel", "pdf", "print"],
      info: true,
      paging: true,
    });
  });
</script>
{% endblock %}

TKTAgent/templates/TKTAgent/resolve_Ticket.html
{% extends 'TKTUsers/base.html' %}
{% load static %}
{% block admin_assign_ticket %}
<div class="container p-5 ">
    <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title bg-white text-center text-primary px-3">
            Resolve Ticket
        </h6>
        <h1 class="mb-3">Resolve Ticket </h1>
    </div>

  <div class="row mb-4">
    <div class="col-6">
      <h5 class="text-start mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAgent:agent_dashboard' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Dashboard</a
        >
      </h5>
    </div>
    <div class="col-6">
      <h5 class="text-end mb-4">
        <a
          class="text-white btn btn-info"
          href="{% url 'TKTAgent:view_tickets_list_agent' %}"
          style="background-color: #886363; border-radius: 10px"
          >Back to Ticket List
        </a>
      </h5>
    </div>
  </div>
   <div>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
        {% endif %}
  </div>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
        <div class="col-6">Website Name</div>
        <div class="col-6">{{Ticket_Form_obj.websitename}}</div>
    </div>
    <div class="row">
        <div class="col-6">Website URL</div>
        <div class="col-6">{{Ticket_Form_obj.websiteurl}}</div>
    </div>
    <div class="row">
        <div class="col-6">Website Description </div>
        <div class="col-6">{{Ticket_Form_obj.website_description}}</div>
    </div>
    <div class="row">
        <div class="col-6">Website Category</div>
        <div class="col-6">{{Ticket_Form_obj.website_category}}</div>
    </div>
    <div class="row">
        <div class="col-6">Issue Related To</div>
        <div class="col-6">{{Ticket_Form_obj.Issue_Related_To}}</div>
    </div>
     <div class="row">
        <div class="col-6">Website Technology</div>
        <div class="col-6">{{Ticket_Form_obj.website_technology}}</div>
    </div>
        <div class="row">
        <div class="col-6">Remark</div>
        <div class="col-6">{{Ticket_Form_obj.ticket_remark}}</div>
    </div>
    <div class="row">
        <div class="col-6">Status</div>
        <div class="col-6">{{Ticket_Form_obj.ticket_status}}</div>
    </div>
        <input class="btn btn-primary" type="submit" value="Assign" />
    </form>


</div>


{% endblock %}