OSTicket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TKTUsers.urls'), name="TKTUsers"),
    path('TKTAdmin/', include('TKTAdmin.urls'), name="TKTAdmin"),
    path('TKTAgent/', include('TKTAgent.urls'), name="TKTAgent"),
]

TKTAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'TKTAdmin'

urlpatterns = [
    path('', home, name="home"),
    path('admin_login', admin_login, name="admin_login"),
    path('admin_dashboard', admin_dashboard, name="admin_dashboard"),
    path('admin_logout', admin_logout, name="admin_logout"),

    path('view_agent_role', view_agent_role, name="view_agent_role"),
    path('create_agent_role', create_agent_role, name="create_agent_role"),
    path('edit_agent_role/<int:id>', edit_agent_role, name="edit_agent_role"),

    path('view_category', view_category, name="view_category"),
    path('create_category', create_category, name="create_category"),
    path('edit_category/<int:id>', edit_category, name="edit_category"),

    path('view_ticket_status_choice', view_ticket_status_choice, name="view_ticket_status_choice"),
    path('create_ticket_status_choice', create_ticket_status_choice, name="create_ticket_status_choice"),
    path('edit_ticket_status_choice/<int:id>', edit_ticket_status_choice, name="edit_ticket_status_choice"),

    path('view_technology_stack', view_technology_stack, name="view_technology_stack"),
    path('create_technology_stack', create_technology_stack, name="create_technology_stack"),
    path('edit_technology_stack/<int:id>', edit_technology_stack, name="edit_technology_stack"),

    path('view_Issue_Category', view_Issue_Category, name="view_Issue_Category"),
    path('create_Issue_Category', create_Issue_Category, name="create_Issue_Category"),
    path('edit_Issue_Category/<int:id>', edit_Issue_Category, name="edit_Issue_Category"),

    path('view_agent_list', view_agent_list, name="view_agent_list"),
    path('create_agent_list', create_agent_list, name="create_agent_list"),
    path('edit_agent_list/<int:id>', edit_agent_list, name="edit_agent_list"),


    path('view_tickets_list', view_tickets_list, name="view_tickets_list"),
    path('assign_ticket/<int:id>', assign_ticket, name="assign_ticket"),


]

TKTUsers/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'TKTUsers'

urlpatterns = [
    path('', home,name="home"),
    path('user_signup', user_signup, name="user_signup"),
    path('user_login', user_login_view, name='user_login'),
    path('user_create_ticket', user_create_ticket, name='user_create_ticket'),
]

TKTUsers/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

##########################################################

class Category(models.Model):
    Category_title = models.CharField(max_length=500)
    Category_created_date = models.DateField(auto_now_add=True, blank=True)
    Category_update_date = models.DateField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Category Title'

    def __str__(self):
        return self.Category_title


##########################################################

class technology_stack(models.Model):
    technology_name = models.CharField(max_length=500)
    technology_stack_created_date = models.DateField(auto_now_add=True, blank=True)
    technology_stack_update_date = models.DateField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Technology Name'

    def __str__(self):
        return self.technology_name


##########################################################

class Issue_Category(models.Model):
    Issue_Category_name = models.CharField(max_length=500)
    Issue_Category_created_date = models.DateField(auto_now_add=True, blank=True)
    Issue_Category_update_date = models.DateField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Issue Category Name'

    def __str__(self):
        return self.Issue_Category_name


##########################################################


##########################################################

class Ticket_status_choice(models.Model):
    status_name = models.CharField(max_length=100)
    Ticket_status_created_date = models.DateField(auto_now_add=True, blank=True)
    Ticket_status_update_date = models.DateField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Ticket Status Choice'

    def __str__(self):
        return self.status_name


##########################################################

class Agent_Role(models.Model):
    Agent_Role_name = models.CharField(max_length=500)
    Agent_Role_created_date = models.DateField(auto_now_add=True, blank=True)
    Agent_Role_update_date = models.DateField(auto_now=True, blank=True)

    class Meta:
        verbose_name_plural = 'Agent_Role_name'

    def __str__(self):
        return self.Agent_Role_name


##########################################################

class Agent(models.Model):
    Agent_name = models.TextField()
    Agent_role = models.ForeignKey(Agent_Role, on_delete=models.CASCADE)
    Agent_created_date = models.DateField(auto_now_add=True, blank=True, null=True)
    Agent_status_choice = (
        ('Active', 'ACTIVE'), ('Deactivated', 'DEACTIVATED'))
    Agent_status = models.CharField(
        choices=Agent_status_choice, max_length=20, )
    Agent_expert = models.ForeignKey(
        technology_stack, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Agent_name'

    def __str__(self):
        return self.Agent_name


##########################################################


# class Ticket_status(models.Model):
#     ticket_token_id = models.ForeignKey(TicketDetail, on_delete=models.CASCADE)
#     ticket_remark = models.TextField()
#     ticket_raised_by = models.ForeignKey(User, on_delete=models.CASCADE)
#     ticket_assigned_to = models.ForeignKey(Agent, on_delete=models.CASCADE)
#     ticket_raised_date = models.DateField(
#         auto_now_add=True, blank=True, null=True)
#     ticket_last_updated_date = models.DateField(
#         auto_now=True, blank=True, null=True)
#     ticket_status = models.ForeignKey(
#         Ticket_status_choice, on_delete=models.CASCADE)
#
#     class Meta:
#         verbose_name_plural = 'ticket_token_id' + 'ticket_raised_by'
#
#     def __str__(self):
#         return str(self.ticket_token_id)

##########################################################

class TicketDetail(models.Model):
    websitename = models.TextField(blank=True,null=True)
    websiteurl = models.TextField(blank=True,null=True)
    website_technology = models.ForeignKey(technology_stack, on_delete=models.CASCADE,blank=True,null=True)
    website_description = models.TextField(blank=True,null=True)
    website_category = models.ForeignKey(Category, on_delete=models.CASCADE,blank=True,null=True)
    Issue_Related_To = models.ForeignKey(Issue_Category, on_delete=models.CASCADE,blank=True,null=True)
    ticket_remark = models.TextField(blank=True,null=True)
    ticket_raised_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True,null=True)
    ticket_assigned_to = models.ForeignKey(Agent, on_delete=models.CASCADE,blank=True,null=True)
    ticket_raised_date = models.DateField(
        auto_now_add=True, blank=True, null=True)
    ticket_last_updated_date = models.DateField(
        auto_now=True, blank=True, null=True)
    ticket_status = models.ForeignKey(
        Ticket_status_choice, on_delete=models.CASCADE,blank=True,null=True)

    class Meta:
        verbose_name_plural = 'Ticket For ' + 'websiteurl'

    def __str__(self):
        return self.websiteurl

TKTUsers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.forms import ModelForm


class UserSignupForm(UserCreationForm):
    username = forms.CharField(label="Your Email ", max_length=30, widget=forms.TextInput(
        attrs={'style': 'border-color: grey;margin-bottom:20px', 'placeholder': 'Enter Your Email',
               'class': 'form-control form-control-lg', 'autocomplete': 'off'}))
    password1 = forms.CharField(label="Your Password ", max_length=30, widget=forms.PasswordInput(
        attrs={'style': 'border-color: grey;margin-bottom:20px', 'placeholder': 'Enter Your Password',
               'class': 'form-control form-control-lg', 'autocomplete': 'off'}))
    password2 = forms.CharField(label="Confirm Password ", max_length=30, widget=forms.PasswordInput(
        attrs={'style': 'border-color: grey;margin-bottom:20px', 'placeholder': 'Confirm Your Password',
               'class': 'form-control form-control-lg', 'autocomplete': 'off'}))

    class Meta:
        model = User
        fields = ['username', ]

    def save(self, commit=True):
        user_obj = super(UserSignupForm, self).save(commit=False)
        user_obj.email = self.cleaned_data["username"]
        user_obj.save()
        return user_obj



class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label="Enter Your Username", max_length=30, widget=forms.TextInput(
        attrs={'style': 'border-color:grey', 'placeholder': 'Enter Username', 'class': 'form-control form-control-lg',
               'autocomplete': 'off'}))

    password = forms.CharField(label="Password", widget=forms.PasswordInput(
        attrs={'style': 'border-color: grey;', 'placeholder': 'Enter Password ',
               'class': 'form-control form-control-lg'}))

    class Meta:
        model = User
        fields = ['username', ]

TKTUsers/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from TKTAdmin.forms import *


# Create your views here.
def home(request):
    return user_signup(request)

##############################################


def user_signup(request):
    if request.method == 'POST':
        UserSignupForm_obj = UserSignupForm(request.POST)
        if UserSignupForm_obj.is_valid():
            UserSignupForm_obj.save()
            messages.success(request, "You are successfully registered")
            return redirect('TKTUsers:user_signup')
        else:
            return render(request, 'TKTUsers/user_signup.html', {'UserSignupForm_obj': UserSignupForm_obj})
    else:
        UserSignupForm_obj = UserSignupForm()
        return render(request, 'TKTUsers/user_signup.html', {'UserSignupForm_obj': UserSignupForm_obj})


##############################################

def user_login_view(request):

    if request.method == 'POST':
        UserLoginForm_obj = UserLoginForm(
            request=request, data=request.POST)
        if UserLoginForm_obj.is_valid():
            uname = UserLoginForm_obj.cleaned_data['username']
            passwd = UserLoginForm_obj.cleaned_data['password']
            user = authenticate(username=uname, password=passwd)
            if user is not None:
                login(request, user)
                messages.success(request, "Login Successfully")
                return redirect('TKTUsers:user_create_ticket')
            else:
                messages.error(request, "User does not exist")
                return redirect('TKTUsers:user_login')
        else:
            messages.error(
                request, "Invalid Details . Please login with correct details")
            return redirect('TKTUsers:user_login')
    else:
        UserLoginForm_obj = UserLoginForm()
        return render(request, 'TKTUsers/user_login.html', {'UserLoginForm_obj': UserLoginForm_obj})

##############################################

def user_create_ticket(request):
    print('##############################')
    print(request.user)
    if request.method=='POST':
        Ticket_Form_obj = Ticket_Form(request.POST)
        if Ticket_Form_obj.is_valid():
            print("Valid DaTA")
            temp_obj = Ticket_Form_obj.save(commit=False)
            temp_obj.ticket_raised_by = request.user
            temp_obj.save()
            messages.success(request,"Created Successfully")
            return redirect('TKTUsers:user_create_ticket')
        else:
            print("INVALID DaTA")
            print(Ticket_Form_obj)
            messages.error(request, "Invalid Details")
            return render(request, 'TKTUsers/user_create_ticket.html', {'Ticket_Form_obj': Ticket_Form_obj})
    else:
        Ticket_Form_obj = Ticket_Form()
        return render(request, 'TKTUsers/user_create_ticket.html',{'Ticket_Form_obj':Ticket_Form_obj})

TKTUsers/templates/TKTUsers/base.html
{% include 'TKTUsers/header.html' %}

<!---PUBLIC APP SECTION ENDS --->
{% block user_signup %}
{% endblock %}

{% block userlogin %}
{% endblock %}

{% block admin_dashboard %}
{% endblock %}

{% block adminlogin %}
{% endblock %}

{% block admin_create_agent_role %}
{% endblock %}


{% block admin_view_agent_role %}
{% endblock%}

{% block admin_edit_agent_role %}
{% endblock %}

{% block admin_view_category %}
{% endblock %}

{% block admin_edit_category %}
{% endblock %}

{% block admin_view_ticket_status_choice %}
{% endblock %}

{% block admin_create_ticket_status_choice %}
{% endblock %}

{% block admin_edit_ticket_status_choice %}
{% endblock %}

{% block admin_view_technology_stack %}
{% endblock %}

{% block admin_create_technology_stack %}
{% endblock %}

{% block admin_edit_technology_stack %}
{% endblock %}

{% block admin_view_Issue_category %}
{% endblock %}

{% block admin_create_issue_category %}
{% endblock %}

{% block admin_edit_issue_category %}
{% endblock %}

{% block admin_view_agent_list %}
{% endblock %}

{% block admin_create_agent%}
{% endblock %}

{% block admin_edit_agent %}
{% endblock %}

{% block admin_view_ticket_list %}
{% endblock %}

{% block admin_assign_ticket %}
{% endblock %}


{% block user_create_ticket %}
{% endblock %}

{% block agentlogin %}
{% endblock %}

{% block agent_dashboard %}
{% endblock %}

{% block agent_view_ticket_list %}
{% endblock %}

{% include 'TKTUsers/footer.html' %}

TKTUsers/templates/TKTUsers/footer.html
{% load static %}
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">

        </div>
        

      </div>
    </div>
    <!-- Footer End -->








    
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    
    <!-- JavaScript Libraries -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'TKTUsers/assets/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'TKTUsers/assets/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'TKTUsers/assets/lib/waypoints/waypoints.min.js' %}"></script>
   <script src="{% static 'TKTUsers/assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'TKTUsers/assets/js/main.js' %}"></script>
</body>

</html>

TKTUsers/templates/TKTUsers/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Help Desk Ticket System</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'TKTUsers/assets/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'TKTUsers/assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


   <!--DATA Tables Scripts and css-->
   <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src=" https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src=" https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <link
      rel="stylesheet"
      href=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css"
    />  


<!-- Customized Bootstrap Stylesheet -->
   <link href="{% static 'TKTUsers/assets/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'TKTUsers/assets/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
        
    <!-- Navbar Start -->
    <nav
      class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0"
    >
      <a
        href="{% url 'TKTUsers:home'%}"
        class="navbar-brand d-flex align-items-center px-4 px-lg-5"
      >
       <div>
          <h2 class="m-0 text-primary">
            <i class="fa fa-book me-3"></i>Help Desk Ticket System
          </h2>
          <p class="m-0 text-primary">Developed & Managed By CDAC & FICCI Team</p>
        </div>  
      </a>
      <button
        type="button"
        class="navbar-toggler me-4"
        data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
         <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="#" class="nav-item nav-link active">Home</a>
             <a href="{% url 'TKTAdmin:admin_login' %}" class="nav-item nav-link active">Admin Login</a>
             <a href="{% url 'TKTUsers:user_login' %}" class="nav-item nav-link active">User Login</a>

                {% comment %} <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Menu</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="#" class="dropdown-item">Menu</a>
                        <a href="#" class="dropdown-item">Menu</a>
                        <a href="#" class="dropdown-item">Menu</a>
                    </div>
                </div> {% endcomment %}
               
            </div>

      </div>
    </nav>

    <div
      class="d-flex py-2"
      style="
        background: #886363;
        color: white;
        height: 40px;
        font-weight: 500;
        outline: none;
      "
    >

    </div>

    <!-- Navbar End -->

TKTUsers/templates/TKTUsers/user_create_ticket.html
{% extends 'TKTUsers/base.html'%}
{% block user_create_ticket %}

<div class="container-fluid p-5 ">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
         <h6 class="section-title bg-white text-center text-primary px-3">Create Ticket</h6>
         <h1 class="mb-5">Create Ticket</h1>
     </div>
      <div class="row d-flex justify-content-center  align-items-center rounded-3">
        <div class="col-md-12 col-lg-10 rounded-9 bg-white p-5 shadow rounded-3 ">
           <div style="color:red">{% if messages %}
            {% for message in messages %}
                <small {% if message.tags %} class = "{{message.tags}}" >{{message}}{% endif %}</small>
            {% endfor %}
             {% endif %}
           </div>


            <form class="row g-3 mt-3" method="POST" action=" " enctype = "multipart/form-data"  novalidate>
                {% csrf_token %}

                <div class="col-md-6">
                  <label for="inputEmail4" class="form-label fs-5 ">Website Name</label>
                  {{Ticket_Form_obj.websitename}}
                </div>
                <div class="col-md-6">
                  <label for="inputPassword4" class="form-label fs-5"> Website URL </label>
                  {{Ticket_Form_obj.websiteurl}}
                </div>


                  <div class="col-md-6 mt-5">
                    <label for="inputPassword4" class="form-label fs-5">Website Category</label>
                    {{Ticket_Form_obj.website_category}}
                  </div>
                <div class="col-6 mt-5">
                        <label for="inputAddress" class="form-label fs-5">Issue Related To</label>
                        {{Ticket_Form_obj.Issue_Related_To}}
                      </div>
                 <div class="col-6 mt-5">
                    <label for="inputEmail4" class="form-label fs-5">Website Technology</label>
                    {{Ticket_Form_obj.website_technology}}
                  </div>
                     <div class="col-6 mt-5">
                    <label for="inputPassword4" class="form-label fs-5">Website Description</label>
                    {{Ticket_Form_obj.website_description}}
                  </div>
                <div class="col-12 justify-content-center  text-center">
                  <button type="submit" class="btn btn-primary">Create Ticket</button>
                </div>
              </form>
         </div>

      </div>
    </div>

{% endblock %}

TKTUsers/templates/TKTUsers/user_login.html
{% extends 'TKTUsers/base.html'%}
{% block userlogin %}

<div class="container my-5 rounded-8">
           <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Login</h6>
            <h1 class="mb-4">Login</h1>
        </div>
     <div class="row justify-content-md-center">
            {% if messages %}
                    {% for message in messages %}
                        <div class="col-8 m-0 p-2 ps-4 fs-6 fw-semibold alert alert-{{message.extra_tags}}">{{message}}</div>
                    {% endfor %}
                {% endif %}
            <div style="color:red" class="col-8">
                {% if UserLoginForm_obj.non_field_errors %}
                    {% for error in UserLoginForm_obj.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong >{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
     </div>
    <div class="row justify-content-md-center">
         <div class='col-8 card px-4 py-8 mx-5 shadow mb-5' style="background-color: #6C3C8203; border-radius:10px !important" >
              <form method="POST" autocomplete="off" novalidate>
                  {% csrf_token %}

              <div class="form-group my-3">
                    <label for="inputEmail" class="mb-1 fs-5 fw-bold px-1">Email Address</label>
                    <div>{{ UserLoginForm_obj.username }}</div>
                    <span class="text-danger">{{ UserLoginForm_obj.username.errors}}</span>
              </div>

             <div class="form-group my-3">
                    <label for="inputPassword" class="mb-1 fs-5 fw-bold px-1">Password <i class="fa fa-question-circle fa-sm" aria-hidden="true" title="Password must contain minimum 8 characters with minimum 1 uppercase character, 1 lowercase character, 1 number and 1 special symbol"></i></label>
                    <div>{{ UserLoginForm_obj.password }} </div>
                    <span class="text-danger">{{ UserLoginForm_obj.password.errors}}</span>
             </div>
              <div class="col-2 ">
                  <button type="submit" class="btn btn-primary mt-2">Login</button>
              </div>
                  <div class="text-center fw-bold fs-6 mt-2">Not Registered User| <a class="text-primary" href="{% url 'TKTUsers:user_signup'%}">Register</a></div>
              </form>
         </div>
    </div>
</div>

{% endblock %}

TKTUsers/templates/TKTUsers/user_signup.html
{% extends 'TKTUsers/base.html' %}

{% block user_signup %}
<div class="container my-5 rounded-8">
           <div class="text-center mt-5 wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Register</h6>
            <h1 class="mb-4">Register</h1>
        </div>
     <div class="row justify-content-md-center">
            {% if messages %}
                    {% for message in messages %}
                        <div class="col-8 m-0 p-2 ps-4 fs-6 fw-semibold alert alert-{{message.extra_tags}}">{{message}}</div>
                    {% endfor %}
                {% endif %}
            <div style="color:red" class="col-8">
                {% if register_form.non_field_errors %}
                    {% for error in register_form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong >{{ error|escape }}</strong>
                        </div>
                    {% endfor %}

                {% endif %}
            </div>
     </div>
    <div class="row justify-content-md-center">
         <div class='col-8 card px-4 py-8 mx-5 shadow mb-5' style="background-color: #6C3C8203; border-radius:10px !important" >
              <form method="POST" autocomplete="off" novalidate>
                  {% csrf_token %}

              <div class="form-group my-3">
                    <label for="inputEmail" class="mb-1 fs-5 fw-bold px-1">Email Address</label>
                    <div>{{ UserSignupForm_obj.username }}</div>
                    <span class="text-danger">{{ UserSignupForm_obj.username.errors}}</span>
              </div>

             <div class="form-group my-3">
                    <label for="inputPassword" class="mb-1 fs-5 fw-bold px-1">Password <i class="fa fa-question-circle fa-sm" aria-hidden="true" title="Password must contain minimum 8 characters with minimum 1 uppercase character, 1 lowercase character, 1 number and 1 special symbol"></i></label>
                    <div>{{ UserSignupForm_obj.password1 }} </div>
                    <span class="text-danger">{{ UserSignupForm_obj.password1.errors}}</span>
             </div>
             <div class="form-group my-3">
                    <label for="inputPassword1" class="mb-1 fs-5 fw-bold px-1">Confirm Password</label>
                    <div>{{ UserSignupForm_obj.password2 }}</div>
                    <span class="text-danger">{{ UserSignupForm_obj.password2.errors}}</span>
             </div>
              <div class="col-2 ">
                  <button type="submit" class="btn btn-primary mt-2 mb-4">Register</button>
              </div>
                  <div class="text-center fw-bold fs-6 mt-2">Already Registered User| <a class="text-primary" href="{% url 'TKTUsers:user_login'%}">Login</a></div>

              </form>
         </div>
    </div>
</div>

{% endblock %}